import assert from 'node:assert/strict';
import fs from 'node:fs';
import { test } from 'node:test';

test('startup supervises v27 read model refresh worker', () => {
  const source = fs.readFileSync('src/index.js', 'utf8');
  const dashboard = fs.readFileSync('src/web/dashboard-server.js', 'utf8');
  const zeaburSupervisor = fs.readFileSync('scripts/run_zeabur_services.sh', 'utf8');

  assert.match(source, /function startPaperReviewSnapshotSidecar/);
  assert.match(source, /function startV27ReadModelRefreshWorker/);
  assert.match(source, /process\.env\.ZEABUR_DATA_DIR\s*\|\|\s*process\.env\.DATA_DIR\s*\|\|\s*'\.\/data'/);
  assert.match(source, /markerGuard:\s*false/);
  assert.match(source, /V27_READ_MODEL_WORKER_STATUS_PATH/);
  assert.match(source, /v27_read_model_worker_status\.json/);
  assert.match(source, /review snapshot and v27 read-model workers remain managed separately/);
  assert.match(source, /\.\.\.alwaysOnWorkers/);
  const alwaysOnReadModelIndex = source.indexOf('...startV27ReadModelRefreshWorker()');
  const sourceShadowEarlyReturnIndex = source.indexOf("if (!envFlag('SOURCE_SHADOW_WORKERS_ENABLED', false))");
  assert.ok(alwaysOnReadModelIndex >= 0, 'v27 read-model worker must be included in always-on workers');
  assert.ok(sourceShadowEarlyReturnIndex >= 0, 'source-shadow early return must remain explicit');
  assert.ok(
    alwaysOnReadModelIndex < sourceShadowEarlyReturnIndex,
    'v27 read-model worker must be reachable before source-shadow workers are disabled',
  );
  assert.match(source, /INDEX_RUNTIME_CHILD_SOURCE_SHADOW_WORKERS_ENABLED/);
  assert.match(source, /PAPER_DB_WRITE_SIDECARS_ENABLED/);
  assert.match(source, /paper DB write sidecars disabled/);
  assert.match(source, /function startPaperDbSnapshotRequestWorker/);
  assert.match(source, /PAPER_DB_SNAPSHOT_REQUEST_WORKER_ENABLED/);
  assert.match(source, /scripts\/paper_db_snapshot_request_worker\.py/);
  assert.match(source, /name:\s*'paper-db-snapshot-request'/);
  assert.match(source, /markerGuard:\s*false/);
  assert.match(source, /PAPER_DB_SNAPSHOT_LOCAL_VERIFY_DIR/);
  assert.match(source, /\/tmp\/paper-db-snapshot-verify/);
  assert.match(source, /startPaperDbSnapshotRequestWorker\(\)/);
  assert.match(zeaburSupervisor, /scripts\/paper_db_snapshot_request_worker\.py/);
  assert.match(zeaburSupervisor, /PAPER_DB_SNAPSHOT_LOCAL_VERIFY_DIR/);
  assert.match(zeaburSupervisor, /\/tmp\/paper-db-snapshot-verify/);
  assert.match(zeaburSupervisor, /export V27_READ_MODEL_REFRESH_WORKER_ENABLED=/);
  assert.match(zeaburSupervisor, /export V27_READ_MODEL_WORKER_STATUS_PATH=/);
  assert.match(source, /envFlag\('PAPER_FAST_LANE_ENABLED', false\)/);
  assert.match(source, /function startRawPathObserverSupervisor/);
  assert.match(source, /RAW_PATH_OBSERVER_ENABLED/);
  assert.match(source, /RAW_PATH_OBSERVER_INTERVAL_SEC/);
  assert.match(source, /RAW_PATH_OBSERVER_RUN_TIMEOUT_SEC/);
  assert.match(source, /raw_path_observer_timeout_/);
  assert.match(source, /scripts\/run-raw-path-observer\.js/);
  assert.match(source, /global\.__rawPathObserverWorkerStatus/);
  assert.match(source, /startRawPathObserverSupervisor\(\)/);
  assert.match(source, /V27_EVENT_LOG_RECOVERY_PREFLIGHT_ENABLED/);
  assert.match(source, /scripts', 'v27_event_log_recover\.py'/);
  assert.match(source, /--quarantine-invalid/);
  assert.match(source, /V27_TELEGRAM_SIGNAL_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-telegram-signal-mirror'/);
  assert.match(source, /scripts\/v27_mirror_telegram_signals\.py/);
  assert.match(source, /'--new-only'/);
  assert.match(source, /V27_TELEGRAM_SIGNAL_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_SOURCE_LABEL_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-source-label-mirror'/);
  assert.match(source, /scripts\/v27_mirror_source_labels\.py/);
  assert.match(source, /V27_SOURCE_LABEL_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_PAPER_TRADE_SOURCE_LABEL_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-paper-trade-source-label-mirror'/);
  assert.match(source, /scripts\/v27_mirror_paper_trade_source_labels\.py/);
  assert.match(source, /V27_PAPER_TRADE_SOURCE_LABEL_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_TRADE_OUTCOME_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-trade-outcome-mirror'/);
  assert.match(source, /scripts\/v27_mirror_trade_outcomes\.py/);
  assert.match(source, /V27_TRADE_OUTCOME_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_STANDARDIZED_STOP_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-standardized-stop-mirror'/);
  assert.match(source, /scripts\/v27_mirror_standardized_stops\.py/);
  assert.match(source, /V27_STANDARDIZED_STOP_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_EX_ANTE_FEASIBILITY_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-ex-ante-feasibility-mirror'/);
  assert.match(source, /scripts\/v27_mirror_ex_ante_feasibility\.py/);
  assert.match(source, /V27_EX_ANTE_FEASIBILITY_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_EARLIEST_ACTIONABLE_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-earliest-actionable-mirror'/);
  assert.match(source, /scripts\/v27_mirror_earliest_actionable_times\.py/);
  assert.match(source, /V27_EARLIEST_ACTIONABLE_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_REALTIME_CLEAN_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-realtime-clean-mirror'/);
  assert.match(source, /scripts\/v27_mirror_realtime_clean\.py/);
  assert.match(source, /V27_REALTIME_CLEAN_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_QUOTE_INTENT_BINDING_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-quote-intent-binding-mirror'/);
  assert.match(source, /scripts\/v27_mirror_quote_intent_bindings\.py/);
  assert.match(source, /V27_QUOTE_INTENT_BINDING_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_RAW_PROVIDER_EVIDENCE_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-raw-provider-evidence-mirror'/);
  assert.match(source, /scripts\/v27_mirror_raw_provider_evidence\.py/);
  assert.match(source, /V27_RAW_PROVIDER_EVIDENCE_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_RAW_PROVIDER_CURSOR_OVERLAP_IDS/);
  assert.match(source, /V27_RAW_PROVIDER_EVIDENCE_TRUSTED_ONLY/);
  assert.match(source, /'--trusted-only'/);
  assert.match(source, /V27_RANDOMNESS_CONTROL_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-randomness-control-mirror'/);
  assert.match(source, /scripts\/v27_mirror_randomness_controls\.py/);
  assert.match(source, /V27_RANDOMNESS_CONTROL_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_IDEMPOTENCY_CONTRACT_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-idempotency-contract-mirror'/);
  assert.match(source, /scripts\/v27_mirror_idempotency_contracts\.py/);
  assert.match(source, /V27_IDEMPOTENCY_CONTRACT_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_EXECUTION_CONTROL_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-execution-control-mirror'/);
  assert.match(source, /scripts\/v27_mirror_execution_control\.py/);
  assert.match(source, /V27_EXECUTION_CONTROL_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_PAPER_LEDGER_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-paper-ledger-mirror'/);
  assert.match(source, /scripts\/v27_mirror_paper_ledgers\.py/);
  assert.match(source, /V27_PAPER_LEDGER_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_PAPER_LEDGER_MIRROR_INITIAL_DELAY_SEC/);
  assert.match(source, /'--skip-verify'/);
  assert.match(source, /V27_RECOVERY_CONTROL_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-recovery-control-mirror'/);
  assert.match(source, /scripts\/v27_mirror_recovery_controls\.py/);
  assert.match(source, /V27_RECOVERY_CONTROL_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_RECOVERY_CONTROL_MISSED_LIMIT/);
  assert.match(source, /V27_PAPER_DECISION_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-paper-decision-mirror'/);
  assert.match(source, /scripts\/v27_mirror_paper_decisions\.py/);
  assert.match(source, /'--include-missed'/);
  assert.match(source, /V27_PAPER_DECISION_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_LIFECYCLE_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-lifecycle-mirror'/);
  assert.match(source, /scripts\/v27_mirror_lifecycle_tracks\.py/);
  assert.match(source, /V27_LIFECYCLE_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_READ_MODEL_REFRESH_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-read-model-refresh'/);
  assert.match(dashboard, /readV27ReadModelWorkerHealth/);
  assert.match(dashboard, /v27_read_model_worker:/);
  assert.match(dashboard, /continuousWorker\.lock_pid_alive\s*\|\|\s*continuousWorker\.running/);
  assert.match(dashboard, /status:\s*'continuous_worker_running'/);
  assert.match(source, /scripts\/v27_read_model_refresh\.py/);
  assert.match(source, /'--loop'/);
  assert.match(source, /V27_EVENT_LOG_DIR/);
  assert.match(source, /V27_READ_MODEL_DIR/);
  assert.match(source, /V27_READ_MODEL_REFRESH_INITIAL_DELAY_SEC/);
  assert.match(source, /V27_READ_MODEL_REFRESH_LOCK_FILE/);
});
