import assert from 'node:assert/strict';
import fs from 'node:fs';
import { test } from 'node:test';

test('startup supervises v27 read model refresh worker', () => {
  const source = fs.readFileSync('src/index.js', 'utf8');

  assert.match(source, /V27_EVENT_LOG_RECOVERY_PREFLIGHT_ENABLED/);
  assert.match(source, /scripts', 'v27_event_log_recover\.py'/);
  assert.match(source, /--quarantine-invalid/);
  assert.match(source, /V27_TELEGRAM_SIGNAL_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-telegram-signal-mirror'/);
  assert.match(source, /scripts\/v27_mirror_telegram_signals\.py/);
  assert.match(source, /'--new-only'/);
  assert.match(source, /V27_TELEGRAM_SIGNAL_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_SOURCE_LABEL_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-source-label-mirror'/);
  assert.match(source, /scripts\/v27_mirror_source_labels\.py/);
  assert.match(source, /V27_SOURCE_LABEL_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_PAPER_TRADE_SOURCE_LABEL_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-paper-trade-source-label-mirror'/);
  assert.match(source, /scripts\/v27_mirror_paper_trade_source_labels\.py/);
  assert.match(source, /V27_PAPER_TRADE_SOURCE_LABEL_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_TRADE_OUTCOME_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-trade-outcome-mirror'/);
  assert.match(source, /scripts\/v27_mirror_trade_outcomes\.py/);
  assert.match(source, /V27_TRADE_OUTCOME_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_STANDARDIZED_STOP_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-standardized-stop-mirror'/);
  assert.match(source, /scripts\/v27_mirror_standardized_stops\.py/);
  assert.match(source, /V27_STANDARDIZED_STOP_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_EX_ANTE_FEASIBILITY_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-ex-ante-feasibility-mirror'/);
  assert.match(source, /scripts\/v27_mirror_ex_ante_feasibility\.py/);
  assert.match(source, /V27_EX_ANTE_FEASIBILITY_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_EARLIEST_ACTIONABLE_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-earliest-actionable-mirror'/);
  assert.match(source, /scripts\/v27_mirror_earliest_actionable_times\.py/);
  assert.match(source, /V27_EARLIEST_ACTIONABLE_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_REALTIME_CLEAN_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-realtime-clean-mirror'/);
  assert.match(source, /scripts\/v27_mirror_realtime_clean\.py/);
  assert.match(source, /V27_REALTIME_CLEAN_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_QUOTE_INTENT_BINDING_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-quote-intent-binding-mirror'/);
  assert.match(source, /scripts\/v27_mirror_quote_intent_bindings\.py/);
  assert.match(source, /V27_QUOTE_INTENT_BINDING_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_IDEMPOTENCY_CONTRACT_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-idempotency-contract-mirror'/);
  assert.match(source, /scripts\/v27_mirror_idempotency_contracts\.py/);
  assert.match(source, /V27_IDEMPOTENCY_CONTRACT_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_EXECUTION_CONTROL_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-execution-control-mirror'/);
  assert.match(source, /scripts\/v27_mirror_execution_control\.py/);
  assert.match(source, /V27_EXECUTION_CONTROL_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_PAPER_LEDGER_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-paper-ledger-mirror'/);
  assert.match(source, /scripts\/v27_mirror_paper_ledgers\.py/);
  assert.match(source, /V27_PAPER_LEDGER_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_PAPER_LEDGER_MIRROR_INITIAL_DELAY_SEC/);
  assert.match(source, /'--skip-verify'/);
  assert.match(source, /V27_PAPER_DECISION_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-paper-decision-mirror'/);
  assert.match(source, /scripts\/v27_mirror_paper_decisions\.py/);
  assert.match(source, /'--include-missed'/);
  assert.match(source, /V27_PAPER_DECISION_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_LIFECYCLE_MIRROR_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-lifecycle-mirror'/);
  assert.match(source, /scripts\/v27_mirror_lifecycle_tracks\.py/);
  assert.match(source, /V27_LIFECYCLE_MIRROR_LOCK_FILE/);
  assert.match(source, /V27_READ_MODEL_REFRESH_WORKER_ENABLED/);
  assert.match(source, /name:\s*'v27-read-model-refresh'/);
  assert.match(source, /scripts\/v27_read_model_refresh\.py/);
  assert.match(source, /'--loop'/);
  assert.match(source, /V27_EVENT_LOG_DIR/);
  assert.match(source, /V27_READ_MODEL_DIR/);
  assert.match(source, /V27_READ_MODEL_REFRESH_INITIAL_DELAY_SEC/);
  assert.match(source, /V27_READ_MODEL_REFRESH_LOCK_FILE/);
});
